Bump all gem dependencies
WeAreFarmGeek/diplomat pull request #215
Opened 2021-02-09 22:40 UTC by Sapr0

Addresses issue #214

2021-02-09 22:57 UTC, pierresouchay requested changes

2021-02-09 22:57 UTC, pierresouchay commented on lib/diplomat/version.rb
> +  VERSION = '3.0.0'
What about 2.5 instead? Would nicely fit with 2.5 ruby compatibility...

2021-02-09 23:03 UTC, pierresouchay commented
@Sapr0 First of all: thanks a lot for this amazing contribution, pushing a lot the level of details.

I have just a few concerns:
 * we don't break the compatibility of the GEM (I mean API compatibility), so maybe a bump to 2.5.x would be enough (moreover, it fits nicely with being compatible with Ruby 2.5)
 * this is an old lib, and many users are using old versions of Ruby. I would like (as far as no security issues are found), to keep the ability for those users to avoid bumping too many versions of many libs, do you think it could be possible to minimize a bit the minimum versions bump? - I mean, is it possible to avoid bumping too much versions as long as we don't rely on new versions to avoid breaking too many users?

Thanks a lot for the contribution, I'll have a deeper look tomorrow (it is midnight here :-)

Regards

2021-02-10 07:45 UTC, Sapr0 commented
Hi @pierresouchay 

I've lowered the gem version to 2.5.0 as you wanted to match the ruby version.

> Do you think it could be possible to minimize a bit the minimum versions bump?

Only `faraday` got bumped from 1.0.1 to 1.3.0
`deep_merge` already had a lose dependency via `>= 1.0.1`

The reset are development dependencies, they are not taken into account when you install this gem.

2021-02-10 08:52 UTC, merged