Add support for default datacenter parameter
WeAreFarmGeek/diplomat pull request #220
Opened 2021-07-13 12:22 UTC by miklinux

This an initial PR is to add support for the default datacenter parameter.
The parameter can be set on initialization and overridden when needed.

I guess I also need to add some test case here, but need some advice here.

2021-07-19 07:48 UTC, pierresouchay requested changes
Hello @miklinux,

Thanks a lot for your contribution. Appart from some complaints from our friend Rubocop, it looks very nice.

About tests, I would recommend adding just a few tests to ensure precedence rules are respected (aka: what happens dc is specific in the config and also in a request).

Thanks a lot for your contribution!

2021-07-19 07:48 UTC, pierresouchay commented on lib/diplomat/rest_client.rb
> +
remove this extra-line (and thus rubocop won't complain)

2021-07-19 07:48 UTC, pierresouchay commented on lib/diplomat/rest_client.rb
> +
Remove this extra-line

2021-07-19 07:48 UTC, pierresouchay commented on lib/diplomat/configuration.rb
> +    # @param dc [String] consul's datacenter to use as default
Please specify somewhere that if nil -> fallback on agent's default DC and specify that using DC in any endpoint overrides this setting

2021-08-24 15:45 UTC, miklinux commented
Hi @pierresouchay,
I've just pushed the requested changes for you to review.

2022-07-26 23:26 UTC, pierresouchay commented
@miklinux can you resolve the conflicts, so we can merge it?

2023-02-07 16:28 UTC, closed without merging